spring:
  datasource:
    driver-class-name: ${jdbc_driver:com.mysql.jdbc.Driver}
    url: ${jdbc_url:jdbc:mysql://localhost:3306/bpm_dev?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false}
    username: ${jdbc_user:bpm}
    password: ${jdbc_password:bpm}
    dbType: ${db_type:mysql}
  activemq:
    broker-url: ${activemq_url:tcp://127.0.0.1:61616}
    in-memory: false
    packages:
      trust-all: true
  redis:
    host: ${redis_host:redis}
    port: ${redis_port:6379}
    password: ${redis_password:}
    database: ${redis_database:0}

eap:
  jwt:
    enabled: ${jwt_enabled:true}